#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\WMI")

//ModuleName = CtlGuid	 (Init called in Function DllMain)
[Dynamic,
 Description("EA IME API"),
 guid("{e2a24a32-00dc-4025-9689-c108c01991c5}"),
 locale("MS\\0x409")]
class EA_IME_API : EventTrace
{
    [Description ("Enable Flags") ,
        ValueDescriptions{
             "Error Flag",
             "Warning Flag",
             "EAAPI Flag",
             "EntryPoint Flag",
             "ImeDDI Flag",
             "TipInterface Flag",
             "FileOp Flag",
             "Misc Flag"},
        DefineValues{
             "Error",
             "Warning",
             "EAAPI",
             "EntryPoint",
             "ImeDDI",
             "TipInterface",
             "FileOp",
             "Misc"},
        Values{
             "Error",
             "Warning",
             "EAAPI",
             "EntryPoint",
             "ImeDDI",
             "TipInterface",
             "FileOp",
             "Misc"},
        ValueMap{
             "0x00000001",
             "0x00000002",
             "0x00000004",
             "0x00000008",
             "0x00000010",
             "0x00000020",
             "0x00000040",
             "0x00000080"}
    ]
    uint32 Flags;
};
