// **************************************************************************
// Copyright (c)  Microsoft Corporation, All Rights Reserved
//
// File:  WmiPerfInst.mof
//
// Description:  WmiPerf instance provider registration
//
// History:
//
// **************************************************************************

#pragma autorecover
#pragma namespace("\\\\.\\root\\cimv2")

instance of __Win32Provider as $P
{
    Name          = "WmiPerfInst";
    ClsId         = "{CA2AF3B4-C15E-412B-B453-557746675FB7}";
    ClientLoadableCLSID = "{FCF7A6F2-3300-4386-9A4F-0DD4E3226507}";
    HostingModel  = "LocalServiceHost";
};

instance of __InstanceProviderRegistration
{
    Provider = $P;

    //read-only
    SupportsGet = TRUE;
    SupportsEnumeration = TRUE;

};

