#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\WMI")

//ModuleName = NtfsLog	 (Init called in Function DriverEntry)
[Dynamic,
 Description("Ntfs_NtfsLog"),
 guid("{b2fc00c4-2941-4d11-983b-b16e8aa4e25d}"),
 locale("MS\\0x409")]
class NtfsLog : EventTrace
{
    uint32 Flags;
};
