#pragma classflags ("forceupdate")
#pragma namespace ( "\\\\.\\root\\StandardCimV2")

#pragma deleteclass("MSFT_3DPrinter",nofail)
#pragma deleteclass("MSFT_Printer",nofail)
#pragma deleteclass("MSFT_AdaptivePrinterPort",nofail)
#pragma deleteclass("MSFT_PrinterPort",nofail)
#pragma deleteclass("MSFT_LocalPrinterPort",nofail)
#pragma deleteclass("MSFT_LprPrinterPort",nofail)
#pragma deleteclass("MSFT_PrintJob",nofail)
#pragma deleteclass("MSFT_PrinterConfiguration",nofail)
#pragma deleteclass("MSFT_PrinterDriver",nofail)
#pragma deleteclass("MSFT_PrinterNfcTag",nofail)
#pragma deleteclass("MSFT_PrinterNfcTagTasks",nofail)
#pragma deleteclass("MSFT_PrinterPortTasks",nofail)
#pragma deleteclass("MSFT_PrinterProperty",nofail)
#pragma deleteclass("MSFT_TcpIpPrinterPort",nofail)
#pragma deleteclass("MSFT_WsdPrinterPort",nofail)
#pragma deleteinstance("__MethodProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\StandardCimV2:__Win32Provider.Name=\\\"MSFT_Printer\\\"\"", nofail)
#pragma deleteinstance("__InstanceProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\StandardCimV2:__Win32Provider.Name=\\\"MSFT_Printer\\\"\"", nofail)
#pragma deleteinstance("__Win32Provider.Name=\"MSFT_Printer\"", nofail)
