//
// This file removes everything under the root\Microsoft\UEV namespace.
// It is meant to be called when User Experience Virtualization is uninstalled.
//

#pragma autorecover

#pragma namespace("\\\\.\\Root\\Microsoft\\UEV")
#pragma deleteclass("EffectiveWindows8App", NOFAIL)
#pragma deleteclass("MachineConfiguredWindows8App", NOFAIL)
#pragma deleteclass("UserConfiguredWindows8App", NOFAIL)

#pragma namespace("\\\\.\\Root\\Microsoft")
#pragma deleteinstance("__Namespace.Name='UEV'", NOFAIL)
