//
// This file removes everything under the root\Microsoft\UEV namespace.
// It is meant to be called when User Experience Virtualization is uninstalled.
//

#pragma autorecover

#pragma namespace("\\\\.\\Root\\Microsoft\\UEV")
#pragma deleteclass("UserSettings", NOFAIL)
#pragma deleteclass("Configuration", NOFAIL)
#pragma deleteclass("UserConfiguration", NOFAIL)
#pragma deleteclass("ComputerConfiguration", NOFAIL)
#pragma deleteclass("SettingsLocationTemplate", NOFAIL)
#pragma deleteclass("ConfigurationItem", NOFAIL)
#pragma deleteclass("UevConfiguration", NOFAIL)

#pragma namespace("\\\\.\\Root\\Microsoft")
#pragma deleteinstance("__Namespace.Name='UEV'", NOFAIL)
