#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\WMI")

//ModuleName = CtlGuidPortableDeviceConnectApi	 (Init called in Function DllMain)
[Dynamic,
 Description("Portable Device Connectivity API Trace"),
 guid("{02FE721A-0725-469E-A26D-37B3C09FAAC1}"),
 locale("MS\\0x409")]
class CtlGuidPortableDeviceConnectApi : EventTrace
{
    [Description ("Enable Flags") ,
        ValueDescriptions{
             "WPD_TRACE_LEVEL_CRITICAL Flag",
             "WPD_TRACE_LEVEL_ERROR Flag",
             "WPD_TRACE_LEVEL_WARNING Flag",
             "WPD_TRACE_LEVEL_ASSERT Flag",
             "WPD_TRACE_LEVEL_FUNCTRACE Flag",
             "WPD_TRACE_LEVEL_INFORMATION Flag",
             "WPD_TRACE_LEVEL_VERBOSE Flag",
             "WPD_TRACE_LEVEL_RESERVED Flag"},
        DefineValues{
             "WPD_TRACE_LEVEL_CRITICAL",
             "WPD_TRACE_LEVEL_ERROR",
             "WPD_TRACE_LEVEL_WARNING",
             "WPD_TRACE_LEVEL_ASSERT",
             "WPD_TRACE_LEVEL_FUNCTRACE",
             "WPD_TRACE_LEVEL_INFORMATION",
             "WPD_TRACE_LEVEL_VERBOSE",
             "WPD_TRACE_LEVEL_RESERVED"},
        Values{
             "WPD_TRACE_LEVEL_CRITICAL",
             "WPD_TRACE_LEVEL_ERROR",
             "WPD_TRACE_LEVEL_WARNING",
             "WPD_TRACE_LEVEL_ASSERT",
             "WPD_TRACE_LEVEL_FUNCTRACE",
             "WPD_TRACE_LEVEL_INFORMATION",
             "WPD_TRACE_LEVEL_VERBOSE",
             "WPD_TRACE_LEVEL_RESERVED"},
        ValueMap{
             "0x00000001",
             "0x00000002",
             "0x00000004",
             "0x00000008",
             "0x00000010",
             "0x00000020",
             "0x00000040",
             "0x00000080"}
    ]
    uint32 Flags;
};

