#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\WMI")

[
   dynamic,
   description("BFE Trace Provider"),
   guid("{106b464a-8043-46b1-8cb8-e92a0cd7a560}"),
   locale("MS\\0x409")
]
class BfeTraceProvider : EventTrace
{
};

[
   dynamic,
   description("FWPKCLNT Trace Provider"),
   guid("{ad33fa19-f2d2-46d1-8f4c-e3c3087e45ad}"),
   locale("MS\\0x409")
]
class FwpkclntTraceProvider : EventTrace
{
};

[
   dynamic,
   description("FWPUCLNT Trace Provider"),
   guid("{5a1600d2-68e5-4de7-bcf4-1c2d215fe0fe}"),
   locale("MS\\0x409")
]
class FwpuclntTraceProvider : EventTrace
{
};

[
   dynamic,
   description("IKEEXT Trace Provider"),
   guid("{106b464d-8043-46b1-8cb8-e92a0cd7a560}"),
   locale("MS\\0x409")
]
class IkeextTraceProvider : EventTrace
{
};

