#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\WMI")

[Dynamic,
 Description("IPMI Provider Trace"),
 guid("{651d672b-e11f-41b7-add3-c2f6a4023672}"),
 locale("MS\\0x409")]
class IPMIPrv : EventTrace
{
    [Description ("Enable Flags"),
        ValueDescriptions{
             "Function Flag",
             "FunctionParameter Flag",
             "FunctionDetail Flag"},
        DefineValues{
             "Function",
             "FunctionParameter",
             "FunctionDetail"},
        Values{
             "Function",
             "FunctionParameter",
             "FunctionDetail"},
        ValueMap{
             "0x00000001",
             "0x00000002",
             "0x00000004"}
    ]
    uint32 Flags;
};
