#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\WMI")

[Dynamic,
 Description("IPMI Driver Trace"),
 guid("{D5C6A3E9-FA9C-434e-9653-165B4FC869E4}"),
 locale("MS\\0x409")]
class IPMIDRIVER : EventTrace
{
    [Description ("Enable Flags"),
        ValueDescriptions{
             "TRACELEVELONE Flag",
             "TRACELEVELTWO Flag"},
        DefineValues{
             "TRACELEVELONE",
             "TRACELEVELTWO"},
        Values{
             "TRACELEVELONE",
             "TRACELEVELTWO"},
        ValueMap{
             "0x00000001",
             "0x00000002"}
    ]
    uint32 Flags;
};
