//*********************************************
// *** Credential Forwarding Provider : CredSsp
//*********************************************
#pragma classflags("forceupdate")
#pragma namespace ("\\\\.\\Root\\WMI")

[abstract,Locale(1033), Description("This is ETW schema root class")] 
class EventTrace
{
};

[Dynamic, 
    Description("Security: TSPkg") : amended,
    Guid("{6165f3e2-ae38-45d4-9b23-6b4818758bd9}"),
    locale("MS\\0x409")]
class TSPkgDebugTrace : EventTrace
{      
    [    
        Description ("Enable Flags") : amended,
        
        ValueDescriptions{
            "Error Flag", "Warning Flag", "Trace Flag", "Credential Flag", 
            "CTXT Flag", "CALLS Flag", "AUTH Flag", "SESS Flag"},
        
        Values{"Error", "Warning", "Trace", "Creds", 
               "Context", "Calls", "Auth", "Session"},
        
        ValueMap{"0x00000001", "0x00000002", "0x00000004", "0x00000008", 
                 "0x00000010", "0x00000020", "0x00000040", "0x00000080"} 
    ]

    uint32 Flags;
};

