<%
//--------------------------------------------------------------------
// Microsoft ADC
//
// Copyright (c) 1997 Microsoft Corporation. All Rights Reserved.
//
//
//
// ADO constants include file for JavaScript
//
//--------------------------------------------------------------------

//---- ADCExecuteOptionEnum Values ----
var adcExecSync=1;
var adcExecAsync=2;

//---- ADCFetchOptionEnum Values ----
var adcFetchUpFront=1;
var adcFetchBackground=2;
var adcFetchAsync=3;

//---- ADCReadyStateEnum Values ----
var adcReadyStateLoaded=2;
var adcReadyStateInteractive=3;
var adcReadyStateComplete=4;
%>