#
# Module manifest for module 'HNS'
#
# Generated by: Microsoft Corporation
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'HostNetworkingService'

# Version number of this module.
ModuleVersion = '1.0.0.1'

# ID used to uniquely identify this module
GUID = 'DB0313A4-E42D-4B51-9D8E-523E839075FD'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) Microsoft Corporation. All rights reserved.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# HelpInfo
HelpInfoUri="https://go.microsoft.com/fwlink/?LinkId=627287"
}
