#pragma namespace ( "\\\\.\\root\\cimv2\\mdm\\dmmap")

#pragma deleteclass("MDM_ActiveSync_User_Accounts01_01",nofail)
#pragma deleteclass("MDM_ActiveSync_User_ContentTypes04_01",nofail)
#pragma deleteclass("MDM_ActiveSync_User_Options03",nofail)
#pragma deleteclass("MDM_AppLocker_ApplicationLaunchRestrictions01_EXE03",nofail)
#pragma deleteclass("MDM_AppLocker_ApplicationLaunchRestrictions01_StoreApps03",nofail)
#pragma deleteclass("MDM_AppLocker_CodeIntegrity03",nofail)
#pragma deleteclass("MDM_AppLocker_DLL03",nofail)
#pragma deleteclass("MDM_AppLocker_EnterpriseDataProtection01_EXE03",nofail)
#pragma deleteclass("MDM_AppLocker_EnterpriseDataProtection01_StoreApps03",nofail)
#pragma deleteclass("MDM_AppLocker_MSI03",nofail)
#pragma deleteclass("MDM_AppLocker_Script03",nofail)
#pragma deleteclass("MDM_AssignedAccess",nofail)
#pragma deleteclass("MDM_BridgeMgmt_Transaction",nofail)
#pragma deleteclass("MDM_ClientCertificateInstall_Install03",nofail)
#pragma deleteclass("MDM_ClientCertificateInstall_PFXCertInstall01_01",nofail)
#pragma deleteclass("MDM_ClientCertificateInstall_SCEP01_01",nofail)
#pragma deleteclass("MDM_DevDetail",nofail)
#pragma deleteclass("MDM_DevDetail_Ext01",nofail)
#pragma deleteclass("MDM_DevDetail_Microsoft02",nofail)
#pragma deleteclass("MDM_DeviceStatus",nofail)
#pragma deleteclass("MDM_DeviceStatus_Antispyware01",nofail)
#pragma deleteclass("MDM_DeviceStatus_Antivirus01",nofail)
#pragma deleteclass("MDM_DeviceStatus_Battery01",nofail)
#pragma deleteclass("MDM_DeviceStatus_CellularIdentities01_01",nofail)
#pragma deleteclass("MDM_DeviceStatus_Compliance01",nofail)
#pragma deleteclass("MDM_DeviceStatus_DeviceGuard01",nofail)
#pragma deleteclass("MDM_DeviceStatus_DMA01",nofail)
#pragma deleteclass("MDM_DeviceStatus_Firewall01",nofail)
#pragma deleteclass("MDM_DeviceStatus_NetworkIdentifiers01_01",nofail)
#pragma deleteclass("MDM_DeviceStatus_OS01",nofail)
#pragma deleteclass("MDM_DeviceStatus_TPM01",nofail)
#pragma deleteclass("MDM_DeviceStatus_UAC01",nofail)
#pragma deleteclass("MDM_EnterpriseAPN_01",nofail)
#pragma deleteclass("MDM_EnterpriseAPN_Settings01",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_AppInstallation01_01",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_AppManagement01",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_AppManagement01_02",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_AppManagement01_03",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_AppSettingPolicy04",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_AutoRepair05",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_AutoUpdateSettings05",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_EffectiveRelease03",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_ReleaseManagement01_01",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_StoreLicenses02_01",nofail)
#pragma deleteclass("MDM_HealthAttestation",nofail)
#pragma deleteclass("MDM_PassportForWork",nofail)
#pragma deleteclass("MDM_PassportForWork_Biometrics01",nofail)
#pragma deleteclass("MDM_PassportForWork_Device_Policies02",nofail)
#pragma deleteclass("MDM_PassportForWork_DeviceUnlock01",nofail)
#pragma deleteclass("MDM_PassportForWork_DynamicLock01",nofail)
#pragma deleteclass("MDM_PassportForWork_ExcludeSecurityDevices03",nofail)
#pragma deleteclass("MDM_PassportForWork_PINComplexity03",nofail)
#pragma deleteclass("MDM_PassportForWork_Policies02",nofail)
#pragma deleteclass("MDM_PassportForWork_Remote03",nofail)
#pragma deleteclass("MDM_PassportForWork_User_Policies02",nofail)
#pragma deleteclass("MDM_Policy_Config01_AboveLock02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Accounts02",nofail)
#pragma deleteclass("MDM_Policy_Config01_ActiveXControls02",nofail)
#pragma deleteclass("MDM_Policy_Config01_ApplicationDefaults02",nofail)
#pragma deleteclass("MDM_Policy_Config01_ApplicationManagement02",nofail)
#pragma deleteclass("MDM_Policy_Config01_AppRuntime02",nofail)
#pragma deleteclass("MDM_Policy_Config01_AppVirtualization02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Audit02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Authentication02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Autoplay02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Bitlocker02",nofail)
#pragma deleteclass("MDM_Policy_Config01_BITS02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Bluetooth02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Browser02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Camera02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Cellular02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Connectivity02",nofail)
#pragma deleteclass("MDM_Policy_Config01_ControlPolicyConflict02",nofail)
#pragma deleteclass("MDM_Policy_Config01_CredentialProviders02",nofail)
#pragma deleteclass("MDM_Policy_Config01_CredentialsDelegation02",nofail)
#pragma deleteclass("MDM_Policy_Config01_CredentialsUI02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Cryptography02",nofail)
#pragma deleteclass("MDM_Policy_Config01_DataProtection02",nofail)
#pragma deleteclass("MDM_Policy_Config01_DataUsage02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Defender02",nofail)
#pragma deleteclass("MDM_Policy_Config01_DeliveryOptimization02",nofail)
#pragma deleteclass("MDM_Policy_Config01_DeviceGuard02",nofail)
#pragma deleteclass("MDM_Policy_Config01_DeviceHealthMonitoring02",nofail)
#pragma deleteclass("MDM_Policy_Config01_DeviceInstallation02",nofail)
#pragma deleteclass("MDM_Policy_Config01_DeviceLock02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Display02",nofail)
#pragma deleteclass("MDM_Policy_Config01_DisplayEnhancement02",nofail)
#pragma deleteclass("MDM_Policy_Config01_DmaGuard02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Eap02",nofail)
#pragma deleteclass("MDM_Policy_Config01_ErrorReporting02",nofail)
#pragma deleteclass("MDM_Policy_Config01_EventLogService02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Experience02",nofail)
#pragma deleteclass("MDM_Policy_Config01_ExploitGuard02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Feeds02",nofail)
#pragma deleteclass("MDM_Policy_Config01_FileExplorer02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Games02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Handwriting02",nofail)
#pragma deleteclass("MDM_Policy_Config01_HumanPresence02",nofail)
#pragma deleteclass("MDM_Policy_Config01_InternetExplorer02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Kerberos02",nofail)
#pragma deleteclass("MDM_Policy_Config01_KioskBrowser02",nofail)
#pragma deleteclass("MDM_Policy_Config01_LanmanWorkstation02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Licensing02",nofail)
#pragma deleteclass("MDM_Policy_Config01_LocalPoliciesSecurityOptions02",nofail)
#pragma deleteclass("MDM_Policy_Config01_LocalUsersAndGroups02",nofail)
#pragma deleteclass("MDM_Policy_Config01_LockDown02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Maps02",nofail)
#pragma deleteclass("MDM_Policy_Config01_MemoryDump02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Messaging02",nofail)
#pragma deleteclass("MDM_Policy_Config01_MixedReality02",nofail)
#pragma deleteclass("MDM_Policy_Config01_MSSecurityGuide02",nofail)
#pragma deleteclass("MDM_Policy_Config01_MSSLegacy02",nofail)
#pragma deleteclass("MDM_Policy_Config01_NetworkIsolation02",nofail)
#pragma deleteclass("MDM_Policy_Config01_NetworkListManager02",nofail)
#pragma deleteclass("MDM_Policy_Config01_NewsAndInterests02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Notifications02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Power02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Printers02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Privacy02",nofail)
#pragma deleteclass("MDM_Policy_Config01_RemoteAssistance02",nofail)
#pragma deleteclass("MDM_Policy_Config01_RemoteDesktop02",nofail)
#pragma deleteclass("MDM_Policy_Config01_RemoteDesktopServices02",nofail)
#pragma deleteclass("MDM_Policy_Config01_RemoteManagement02",nofail)
#pragma deleteclass("MDM_Policy_Config01_RemoteProcedureCall02",nofail)
#pragma deleteclass("MDM_Policy_Config01_RemoteShell02",nofail)
#pragma deleteclass("MDM_Policy_Config01_RestrictedGroups02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Search02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Security02",nofail)
#pragma deleteclass("MDM_Policy_Config01_ServiceControlManager02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Settings02",nofail)
#pragma deleteclass("MDM_Policy_Config01_SmartScreen02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Speech02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Start02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Storage02",nofail)
#pragma deleteclass("MDM_Policy_Config01_System02",nofail)
#pragma deleteclass("MDM_Policy_Config01_SystemServices02",nofail)
#pragma deleteclass("MDM_Policy_Config01_TaskManager02",nofail)
#pragma deleteclass("MDM_Policy_Config01_TaskScheduler02",nofail)
#pragma deleteclass("MDM_Policy_Config01_TenantRestrictions02",nofail)
#pragma deleteclass("MDM_Policy_Config01_TextInput02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Theme02",nofail)
#pragma deleteclass("MDM_Policy_Config01_TimeLanguageSettings02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Troubleshooting02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Update02",nofail)
#pragma deleteclass("MDM_Policy_Config01_UserModel02",nofail)
#pragma deleteclass("MDM_Policy_Config01_UserRights02",nofail)
#pragma deleteclass("MDM_Policy_Config01_VirtualizationBasedTechnology02",nofail)
#pragma deleteclass("MDM_Policy_Config01_Wifi02",nofail)
#pragma deleteclass("MDM_Policy_Config01_WindowsAutopilot02",nofail)
#pragma deleteclass("MDM_Policy_Config01_WindowsConnectionManager02",nofail)
#pragma deleteclass("MDM_Policy_Config01_WindowsDefenderSecurityCenter02",nofail)
#pragma deleteclass("MDM_Policy_Config01_WindowsInkWorkspace02",nofail)
#pragma deleteclass("MDM_Policy_Config01_WindowsLogon02",nofail)
#pragma deleteclass("MDM_Policy_Config01_WindowsPowerShell02",nofail)
#pragma deleteclass("MDM_Policy_Config01_WindowsSandbox02",nofail)
#pragma deleteclass("MDM_Policy_Config01_WirelessDisplay02",nofail)
#pragma deleteclass("MDM_Policy_Result01_AboveLock02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Accounts02",nofail)
#pragma deleteclass("MDM_Policy_Result01_ActiveXControls02",nofail)
#pragma deleteclass("MDM_Policy_Result01_ApplicationDefaults02",nofail)
#pragma deleteclass("MDM_Policy_Result01_ApplicationManagement02",nofail)
#pragma deleteclass("MDM_Policy_Result01_AppRuntime02",nofail)
#pragma deleteclass("MDM_Policy_Result01_AppVirtualization02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Audit02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Authentication02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Autoplay02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Bitlocker02",nofail)
#pragma deleteclass("MDM_Policy_Result01_BITS02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Bluetooth02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Browser02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Camera02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Cellular02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Connectivity02",nofail)
#pragma deleteclass("MDM_Policy_Result01_ControlPolicyConflict02",nofail)
#pragma deleteclass("MDM_Policy_Result01_CredentialProviders02",nofail)
#pragma deleteclass("MDM_Policy_Result01_CredentialsDelegation02",nofail)
#pragma deleteclass("MDM_Policy_Result01_CredentialsUI02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Cryptography02",nofail)
#pragma deleteclass("MDM_Policy_Result01_DataProtection02",nofail)
#pragma deleteclass("MDM_Policy_Result01_DataUsage02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Defender02",nofail)
#pragma deleteclass("MDM_Policy_Result01_DeliveryOptimization02",nofail)
#pragma deleteclass("MDM_Policy_Result01_DeviceGuard02",nofail)
#pragma deleteclass("MDM_Policy_Result01_DeviceHealthMonitoring02",nofail)
#pragma deleteclass("MDM_Policy_Result01_DeviceInstallation02",nofail)
#pragma deleteclass("MDM_Policy_Result01_DeviceLock02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Display02",nofail)
#pragma deleteclass("MDM_Policy_Result01_DisplayEnhancement02",nofail)
#pragma deleteclass("MDM_Policy_Result01_DmaGuard02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Eap02",nofail)
#pragma deleteclass("MDM_Policy_Result01_ErrorReporting02",nofail)
#pragma deleteclass("MDM_Policy_Result01_EventLogService02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Experience02",nofail)
#pragma deleteclass("MDM_Policy_Result01_ExploitGuard02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Feeds02",nofail)
#pragma deleteclass("MDM_Policy_Result01_FileExplorer02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Games02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Handwriting02",nofail)
#pragma deleteclass("MDM_Policy_Result01_HumanPresence02",nofail)
#pragma deleteclass("MDM_Policy_Result01_InternetExplorer02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Kerberos02",nofail)
#pragma deleteclass("MDM_Policy_Result01_KioskBrowser02",nofail)
#pragma deleteclass("MDM_Policy_Result01_LanmanWorkstation02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Licensing02",nofail)
#pragma deleteclass("MDM_Policy_Result01_LocalPoliciesSecurityOptions02",nofail)
#pragma deleteclass("MDM_Policy_Result01_LocalUsersAndGroups02",nofail)
#pragma deleteclass("MDM_Policy_Result01_LockDown02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Maps02",nofail)
#pragma deleteclass("MDM_Policy_Result01_MemoryDump02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Messaging02",nofail)
#pragma deleteclass("MDM_Policy_Result01_MixedReality02",nofail)
#pragma deleteclass("MDM_Policy_Result01_MSSecurityGuide02",nofail)
#pragma deleteclass("MDM_Policy_Result01_MSSLegacy02",nofail)
#pragma deleteclass("MDM_Policy_Result01_NetworkIsolation02",nofail)
#pragma deleteclass("MDM_Policy_Result01_NetworkListManager02",nofail)
#pragma deleteclass("MDM_Policy_Result01_NewsAndInterests02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Notifications02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Power02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Printers02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Privacy02",nofail)
#pragma deleteclass("MDM_Policy_Result01_RemoteAssistance02",nofail)
#pragma deleteclass("MDM_Policy_Result01_RemoteDesktop02",nofail)
#pragma deleteclass("MDM_Policy_Result01_RemoteDesktopServices02",nofail)
#pragma deleteclass("MDM_Policy_Result01_RemoteManagement02",nofail)
#pragma deleteclass("MDM_Policy_Result01_RemoteProcedureCall02",nofail)
#pragma deleteclass("MDM_Policy_Result01_RemoteShell02",nofail)
#pragma deleteclass("MDM_Policy_Result01_RestrictedGroups02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Search02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Security02",nofail)
#pragma deleteclass("MDM_Policy_Result01_ServiceControlManager02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Settings02",nofail)
#pragma deleteclass("MDM_Policy_Result01_SmartScreen02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Speech02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Start02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Storage02",nofail)
#pragma deleteclass("MDM_Policy_Result01_System02",nofail)
#pragma deleteclass("MDM_Policy_Result01_SystemServices02",nofail)
#pragma deleteclass("MDM_Policy_Result01_TaskManager02",nofail)
#pragma deleteclass("MDM_Policy_Result01_TaskScheduler02",nofail)
#pragma deleteclass("MDM_Policy_Result01_TenantRestrictions02",nofail)
#pragma deleteclass("MDM_Policy_Result01_TextInput02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Theme02",nofail)
#pragma deleteclass("MDM_Policy_Result01_TimeLanguageSettings02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Troubleshooting02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Update02",nofail)
#pragma deleteclass("MDM_Policy_Result01_UserModel02",nofail)
#pragma deleteclass("MDM_Policy_Result01_UserRights02",nofail)
#pragma deleteclass("MDM_Policy_Result01_VirtualizationBasedTechnology02",nofail)
#pragma deleteclass("MDM_Policy_Result01_Wifi02",nofail)
#pragma deleteclass("MDM_Policy_Result01_WindowsAutopilot02",nofail)
#pragma deleteclass("MDM_Policy_Result01_WindowsConnectionManager02",nofail)
#pragma deleteclass("MDM_Policy_Result01_WindowsDefenderSecurityCenter02",nofail)
#pragma deleteclass("MDM_Policy_Result01_WindowsInkWorkspace02",nofail)
#pragma deleteclass("MDM_Policy_Result01_WindowsLogon02",nofail)
#pragma deleteclass("MDM_Policy_Result01_WindowsPowerShell02",nofail)
#pragma deleteclass("MDM_Policy_Result01_WindowsSandbox02",nofail)
#pragma deleteclass("MDM_Policy_Result01_WirelessDisplay02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_ApplicationManagement02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_AttachmentManager02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Authentication02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Browser02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_CredentialsUI02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Desktop02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Display02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Education02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_EnterpriseCloudPrint02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Experience02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_FileExplorer02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_InternetExplorer02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Multitasking02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Notifications02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Printers02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Privacy02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_RemoteDesktop02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Security02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Settings02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Start02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_Storage02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_System02",nofail)
#pragma deleteclass("MDM_Policy_User_Config01_TimeLanguageSettings02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_ApplicationManagement02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_AttachmentManager02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Authentication02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Browser02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_CredentialsUI02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Desktop02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Display02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Education02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_EnterpriseCloudPrint02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Experience02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_FileExplorer02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_InternetExplorer02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Multitasking02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Notifications02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Printers02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Privacy02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_RemoteDesktop02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Security02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Settings02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Start02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_Storage02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_System02",nofail)
#pragma deleteclass("MDM_Policy_User_Result01_TimeLanguageSettings02",nofail)
#pragma deleteclass("MDM_RemoteWipe",nofail)
#pragma deleteclass("MDM_VPNv2_01",nofail)
#pragma deleteclass("MDM_VPNv2_APNBinding02",nofail)
#pragma deleteclass("MDM_VPNv2_AppTriggerList02_App04",nofail)
#pragma deleteclass("MDM_VPNv2_Authentication03",nofail)
#pragma deleteclass("MDM_VPNv2_Certificate04",nofail)
#pragma deleteclass("MDM_VPNv2_CryptographySuite03",nofail)
#pragma deleteclass("MDM_VPNv2_DeviceCompliance02",nofail)
#pragma deleteclass("MDM_VPNv2_DomainNameInformationList02_01",nofail)
#pragma deleteclass("MDM_VPNv2_Eap04",nofail)
#pragma deleteclass("MDM_VPNv2_Manual03",nofail)
#pragma deleteclass("MDM_VPNv2_NativeProfile02",nofail)
#pragma deleteclass("MDM_VPNv2_PluginProfile02",nofail)
#pragma deleteclass("MDM_VPNv2_Proxy02",nofail)
#pragma deleteclass("MDM_VPNv2_RouteList02_01",nofail)
#pragma deleteclass("MDM_VPNv2_Sso03",nofail)
#pragma deleteclass("MDM_VPNv2_TrafficFilterList02_01",nofail)
#pragma deleteclass("MDM_VPNv2_TrafficFilterList02_App04",nofail)
#pragma deleteclass("MDM_VPNv2_User_01",nofail)
#pragma deleteclass("MDM_WindowsLicensing",nofail)
#pragma deleteclass("MDM_WindowsLicensing_Subscriptions01_01",nofail)
#pragma deleteinstance("__MethodProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\cimv2\\\\mdm\\\\dmmap:__Win32Provider.Name=\\\"DMWmiBridgeProv\\\"\"", nofail)
#pragma deleteinstance("__InstanceProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\cimv2\\\\mdm\\\\dmmap:__Win32Provider.Name=\\\"DMWmiBridgeProv\\\"\"", nofail)
#pragma deleteinstance("__Win32Provider.Name=\"DMWmiBridgeProv\"", nofail)
