#pragma namespace ( "\\\\.\\root\\cimv2\\mdm\\dmmap")

#pragma deleteclass("MDM_ApplicationControl",nofail)
#pragma deleteclass("MDM_ApplicationControl_Policies01_01",nofail)
#pragma deleteclass("MDM_ApplicationControl_PolicyIDs03",nofail)
#pragma deleteclass("MDM_ApplicationControl_PolicyInfo03",nofail)
#pragma deleteclass("MDM_ApplicationControl_Token03",nofail)
#pragma deleteclass("MDM_ApplicationControl_TokenInfo03",nofail)
#pragma deleteclass("MDM_ApplicationControl_Tokens01_01",nofail)
#pragma deleteclass("MDM_BitLocker",nofail)
#pragma deleteclass("MDM_BitLocker_Status01",nofail)
#pragma deleteclass("MDM_DeviceManageability_Provider01_01",nofail)
#pragma deleteclass("MDM_DeviceUpdateCenter_DesiredUpdates01",nofail)
#pragma deleteclass("MDM_DeviceUpdateCenter_Enrollment01",nofail)
#pragma deleteclass("MDM_EnrollmentStatusTracking_PolicyProviders02_01",nofail)
#pragma deleteclass("MDM_EnrollmentStatusTracking_PolicyProviders03_01",nofail)
#pragma deleteclass("MDM_EnrollmentStatusTracking_Setup01",nofail)
#pragma deleteclass("MDM_EnrollmentStatusTracking_TrackedResourceTypes04",nofail)
#pragma deleteclass("MDM_EnrollmentStatusTracking_Tracking03_02",nofail)
#pragma deleteclass("MDM_EnterpriseDataProtection",nofail)
#pragma deleteclass("MDM_EnterpriseDataProtection_Settings01",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_AppInstallation01_01",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_AppManagement01",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_AppManagement01_02",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_AppManagement01_03",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_AppSettingPolicy04",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_EffectiveRelease05",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_ReleaseManagement03_01",nofail)
#pragma deleteclass("MDM_EnterpriseModernAppManagement_StoreLicenses02_01",nofail)
#pragma deleteclass("MDM_eUICCs_01",nofail)
#pragma deleteclass("MDM_eUICCs_Actions02",nofail)
#pragma deleteclass("MDM_eUICCs_DownloadServers02_01",nofail)
#pragma deleteclass("MDM_eUICCs_Policies02",nofail)
#pragma deleteclass("MDM_eUICCs_Profiles02_01",nofail)
#pragma deleteclass("MDM_Firewall_Action04",nofail)
#pragma deleteclass("MDM_Firewall_Addresses03_01",nofail)
#pragma deleteclass("MDM_Firewall_App04",nofail)
#pragma deleteclass("MDM_Firewall_DomainProfile02",nofail)
#pragma deleteclass("MDM_Firewall_FirewallRules02_01",nofail)
#pragma deleteclass("MDM_Firewall_Global02",nofail)
#pragma deleteclass("MDM_Firewall_PrivateProfile02",nofail)
#pragma deleteclass("MDM_Firewall_PublicProfile02",nofail)
#pragma deleteclass("MDM_LanguagePackManagement_Install01_01",nofail)
#pragma deleteclass("MDM_LanguagePackManagement_InstalledLanguages01_01",nofail)
#pragma deleteclass("MDM_LanguagePackManagement_LanguageSettings01",nofail)
#pragma deleteclass("MDM_MultiSIM_01",nofail)
#pragma deleteclass("MDM_MultiSIM_Policies02",nofail)
#pragma deleteclass("MDM_MultiSIM_Slots02_01",nofail)
#pragma deleteclass("MDM_Personalization",nofail)
#pragma deleteclass("MDM_Reboot",nofail)
#pragma deleteclass("MDM_Reboot_Schedule01",nofail)
#pragma deleteclass("MDM_RemoteFind",nofail)
#pragma deleteclass("MDM_RemoteFind_Location01",nofail)
#pragma deleteclass("MDM_Reporting_EnterpriseDataProtection01_RetrieveByCount02",nofail)
#pragma deleteclass("MDM_Reporting_EnterpriseDataProtection01_RetrieveByTimeRange02",nofail)
#pragma deleteclass("MDM_Reporting_SecurityAuditing01_RetrieveByCount02",nofail)
#pragma deleteclass("MDM_Reporting_SecurityAuditing01_RetrieveByTimeRange02",nofail)
#pragma deleteclass("MDM_SecureAssessment",nofail)
#pragma deleteclass("MDM_SharedPC",nofail)
#pragma deleteclass("MDM_Update",nofail)
#pragma deleteclass("MDM_Update_ApprovedUpdates01_01",nofail)
#pragma deleteclass("MDM_Update_FailedUpdates01_01",nofail)
#pragma deleteclass("MDM_Update_InstallableUpdates01_01",nofail)
#pragma deleteclass("MDM_Update_PendingRebootUpdates01_01",nofail)
#pragma deleteclass("MDM_Update_Rollback01",nofail)
#pragma deleteclass("MDM_Win32CompatibilityAppraiser_AppraiserConfigurationDiagnosis02",nofail)
#pragma deleteclass("MDM_Win32CompatibilityAppraiser_CompatibilityAppraiser01",nofail)
#pragma deleteclass("MDM_Win32CompatibilityAppraiser_UniversalTelemetryClient01",nofail)
#pragma deleteclass("MDM_Win32CompatibilityAppraiser_UtcConfigurationDiagnosis02",nofail)
#pragma deleteclass("MDM_Win32CompatibilityAppraiser_WerConfigurationDiagnosis02",nofail)
#pragma deleteclass("MDM_Win32CompatibilityAppraiser_WindowsErrorReporting01",nofail)
#pragma deleteclass("MDM_WindowsAdvancedThreatProtection",nofail)
#pragma deleteclass("MDM_WindowsAdvancedThreatProtection_Configuration01",nofail)
#pragma deleteclass("MDM_WindowsAdvancedThreatProtection_DeviceTagging01",nofail)
#pragma deleteclass("MDM_WindowsAdvancedThreatProtection_HealthState01",nofail)
#pragma deleteclass("MDM_WindowsDefenderApplicationGuard",nofail)
#pragma deleteclass("MDM_WindowsDefenderApplicationGuard_Audit01",nofail)
#pragma deleteclass("MDM_WindowsDefenderApplicationGuard_Settings01",nofail)
#pragma deleteclass("MDM_WindowsIoT_SoftRealTimeProperties01",nofail)
#pragma deleteinstance("__MethodProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\cimv2\\\\mdm\\\\dmmap:__Win32Provider.Name=\\\"DMWmiBridgeProv1\\\"\"", nofail)
#pragma deleteinstance("__InstanceProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\cimv2\\\\mdm\\\\dmmap:__Win32Provider.Name=\\\"DMWmiBridgeProv1\\\"\"", nofail)
#pragma deleteinstance("__Win32Provider.Name=\"DMWmiBridgeProv1\"", nofail)
