#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\WMI")

[Dynamic,
 Description("Microsoft-Windows-LLTD-MapperIO"),
 guid("{0741C7BE-DAAC-4A5b-B00A-4BD9A2D89D0E}"),
 locale("MS\\0x409")]
class LLTDIO : EventTrace
{
    [Description ("Enable Flags"),
        ValueDescriptions{
             "TRACE_CLASS_CALL Flag",
             "TRACE_CLASS_DISPATCH Flag",
             "TRACE_CLASS_BINDING Flag",
             "TRACE_CLASS_CONTEXT Flag",
             "TRACE_CLASS_QOS Flag",
             "TRACE_CLASS_REQUEST Flag"},
        DefineValues{
             "TRACE_CLASS_CALL",
             "TRACE_CLASS_DISPATCH",
             "TRACE_CLASS_BINDING",
             "TRACE_CLASS_CONTEXT",
             "TRACE_CLASS_QOS",
             "TRACE_CLASS_REQUEST"},
        Values{
             "TRACE_CLASS_CALL",
             "TRACE_CLASS_DISPATCH",
             "TRACE_CLASS_BINDING",
             "TRACE_CLASS_CONTEXT",
             "TRACE_CLASS_QOS",
             "TRACE_CLASS_REQUEST"},
        ValueMap{
             "0x00000001",
             "0x00000002",
             "0x00000004",
             "0x00000008",
             "0x00000010",
             "0x00000020"}
    ]
    uint32 Flags;
};
