#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\WMI")

[Dynamic,
 Description("Microsoft-Windows-LLTD-Responder"),
 guid("{E159FC63-02FE-42F3-A234-028B9B8561CB}"),
 locale("MS\\0x409")]
class RSPNDR : EventTrace
{
    [Description ("Enable Flags"),
        ValueDescriptions{
             "TRACE_CLASS_CALL Flag",
             "TRACE_CLASS_DISPATCH Flag",
             "TRACE_CLASS_REQUEST Flag",
             "TRACE_CLASS_BINDING Flag",
             "TRACE_CLASS_SESSION Flag",
             "TRACE_CLASS_QUIESCENT Flag",
             "TRACE_CLASS_HELLO Flag",
             "TRACE_CLASS_COMMAND Flag",
             "TRACE_CLASS_EMIT Flag",
             "TRACE_CLASS_THREAD Flag",
             "TRACE_CLASS_TIMER Flag",
             "TRACE_CLASS_QOS Flag",
             "TRACE_CLASS_NLC Flag"},
        DefineValues{
             "TRACE_CLASS_CALL",
             "TRACE_CLASS_DISPATCH",
             "TRACE_CLASS_REQUEST",
             "TRACE_CLASS_BINDING",
             "TRACE_CLASS_SESSION",
             "TRACE_CLASS_QUIESCENT",
             "TRACE_CLASS_HELLO",
             "TRACE_CLASS_COMMAND",
             "TRACE_CLASS_EMIT",
             "TRACE_CLASS_THREAD",
             "TRACE_CLASS_TIMER",
             "TRACE_CLASS_QOS",
             "TRACE_CLASS_NLC"},
        Values{
             "TRACE_CLASS_CALL",
             "TRACE_CLASS_DISPATCH",
             "TRACE_CLASS_REQUEST",
             "TRACE_CLASS_BINDING",
             "TRACE_CLASS_SESSION",
             "TRACE_CLASS_QUIESCENT",
             "TRACE_CLASS_HELLO",
             "TRACE_CLASS_COMMAND",
             "TRACE_CLASS_EMIT",
             "TRACE_CLASS_THREAD",
             "TRACE_CLASS_TIMER",
             "TRACE_CLASS_QOS",
             "TRACE_CLASS_NLC"},
        ValueMap{
             "0x00000001",
             "0x00000002",
             "0x00000004",
             "0x00000008",
             "0x00000010",
             "0x00000020",
             "0x00000040",
             "0x00000080",
             "0x00000100",
             "0x00000200",
             "0x00000400",
             "0x00000800",
             "0x00001000"}
    ]
    uint32 Flags;
};
