#pragma autorecover
#pragma namespace("\\\\.\\Root\\WMI")
  
#pragma DeleteClass("LpcTraceGuid", NOFAIL)
#pragma DeleteClass("PlatformLibraryTraceGuid", NOFAIL)
#pragma DeleteClass("FrameworkTraceGuid", NOFAIL)
#pragma DeleteClass("HostProcessTraceGuid", NOFAIL)
#pragma DeleteClass("LpcDriverTraceGuid", NOFAIL)
#pragma DeleteClass("ReflectorTraceGuid", NOFAIL)
#pragma DeleteClass("TestTraceGuid", NOFAIL)
#pragma DeleteClass("DriverManagerTraceGuid", NOFAIL)
#pragma DeleteClass("WdfCoreTraceGuid", NOFAIL)

