//#PRAGMA AUTORECOVER Note that AUTORECOVER is not required as this file does not register anything to WMI Repository (per NiBhat 2006/06/27)

#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\WMI")


#pragma deleteclass("MSMQ_GENERAL", nofail)
#pragma deleteclass("MSMQ_AC", nofail)
#pragma deleteclass("MSMQ_NETWORKING", nofail)
#pragma deleteclass("MSMQ_SRMP", nofail)
#pragma deleteclass("MSMQ_RPC", nofail)
#pragma deleteclass("MSMQ_DS", nofail)
#pragma deleteclass("MSMQ_SECURITY", nofail)
#pragma deleteclass("MSMQ_ROUTING", nofail)
#pragma deleteclass("MSMQ_XACT", nofail)
#pragma deleteclass("MSMQ_XACT_SEND", nofail)
#pragma deleteclass("MSMQ_XACT_RCV", nofail)
#pragma deleteclass("MSMQ_XACT_LOG", nofail)
#pragma deleteclass("MSMQ_LOG", nofail)
#pragma deleteclass("MSMQ_PROFILING", nofail)
#pragma deleteclass("MSMQ_ERRORLOGGING", nofail)



