#pragma classflags ("safeupdate")

#pragma namespace ("\\\\.\\root\\Microsoft\\Windows\\Storage\\PT\\Alt")

#pragma deleteinstance("__MethodProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\Microsoft\\\\Windows\\\\Storage\\\\PT\\\\Alt:__Win32Provider.Name=\\\"DelegatorProvider\\\"\"", nofail)
#pragma deleteinstance("__InstanceProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\Microsoft\\\\Windows\\\\Storage\\\\PT\\\\Alt:__Win32Provider.Name=\\\"DelegatorProvider\\\"\"", nofail)
#pragma deleteinstance("__ClassProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\Microsoft\\\\Windows\\\\Storage\\\\PT\\\\Alt:__Win32Provider.Name=\\\"DelegatorProvider\\\"\"", nofail)
#pragma deleteinstance("__Win32Provider.Name=\"DelegatorProvider\"", nofail)

#pragma namespace ("\\\\.\\root\\Microsoft\\Windows\\Storage\\PT")

#pragma deleteinstance("__Namespace.Name=\"Alt\"", nofail)

#pragma deleteinstance("__MethodProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\Microsoft\\\\Windows\\\\Storage\\\\PT:__Win32Provider.Name=\\\"DelegatorProvider\\\"\"", nofail)
#pragma deleteinstance("__InstanceProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\Microsoft\\\\Windows\\\\Storage\\\\PT:__Win32Provider.Name=\\\"DelegatorProvider\\\"\"", nofail)
#pragma deleteinstance("__ClassProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\Microsoft\\\\Windows\\\\Storage\\\\PT:__Win32Provider.Name=\\\"DelegatorProvider\\\"\"", nofail)
#pragma deleteinstance("__Win32Provider.Name=\"DelegatorProvider\"", nofail)

#pragma namespace ( "\\\\.\\root\\Microsoft\\Windows\\Storage")

#pragma deleteinstance("__Namespace.Name=\"PT\"", nofail)
