#pragma autorecover

#pragma classflags("forceupdate")

#pragma namespace("\\\\.\\root\\Microsoft\\Windows\\Storage")

instance of __Namespace
{
    Name = "PT";
};

#pragma namespace("\\\\.\\root\\Microsoft\\Windows\\Storage\\PT")

[RequiresEncryption(TRUE)]
instance of __systemSecurity
{
};

instance of __Win32Provider as $P
{
    Name = "DelegatorProvider";
    ClsId = "{03E7DAD7-17A6-4F91-A879-F276B6FD62F8}";
    UnloadTimeout = "00000001000000.000000:000";
};

instance of __ClassProviderRegistration
{
    Provider = $P;
    SupportsGet = TRUE;
    SupportsEnumeration = TRUE;
    ResultSetQueries = { "SELECT * FROM meta_class" };
    ReferencedSetQueries = { "SELECT * FROM meta_class" };
};

instance of __InstanceProviderRegistration
{
    Provider = $P;
    SupportsPut = TRUE;
    SupportsGet = TRUE;
    SupportsDelete = TRUE;
    SupportsEnumeration = TRUE;
    QuerySupportLevels = { "WQL:UnarySelect" };
};

instance of __MethodProviderRegistration
{
    Provider = $P;
};

instance of __Namespace
{
    Name = "Alt";
};

#pragma namespace("\\\\.\\root\\Microsoft\\Windows\\Storage\\PT\\Alt")

instance of __Win32Provider as $Q
{
    Name = "DelegatorProvider";
    ClsId = "{03E7DAD7-17A6-4F91-A879-F276B6FD62F8}";
    UnloadTimeout = "00000001000000.000000:000";
};

instance of __ClassProviderRegistration
{
    Provider = $Q;
    SupportsGet = TRUE;
    SupportsEnumeration = TRUE;
    ResultSetQueries = { "SELECT * FROM meta_class" };
    ReferencedSetQueries = { "SELECT * FROM meta_class" };
};

instance of __InstanceProviderRegistration
{
    Provider = $Q;
    SupportsPut = TRUE;
    SupportsGet = TRUE;
    SupportsDelete = TRUE;
    SupportsEnumeration = TRUE;
    QuerySupportLevels = { "WQL:UnarySelect" };
};

instance of __MethodProviderRegistration
{
    Provider = $Q;
};
