#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\WMI")

[Dynamic,
 Description("Microsoft-Windows-LLTD-Mapper"),
 guid("{CCC64809-6B5F-4c1b-AB39-336904DA9B3B}"),
 locale("MS\\0x409")]
class LLTDSVC : EventTrace
{
    [Description ("Enable Flags"),
        ValueDescriptions{
             "TRACE_CLASS_CALL Flag",
             "TRACE_CLASS_INIT Flag",
             "TRACE_CLASS_ENGINE Flag",
             "TRACE_CLASS_PACKET Flag",
             "TRACE_CLASS_PROTOCOL Flag",
             "TRACE_CLASS_ALGORITHM Flag",
             "TRACE_CLASS_SESSION Flag",
             "TRACE_CLASS_TRANSACTION Flag",
             "TRACE_CLASS_MAPPING Flag"},
        DefineValues{
             "TRACE_CLASS_CALL",
             "TRACE_CLASS_INIT",
             "TRACE_CLASS_ENGINE",
             "TRACE_CLASS_PACKET",
             "TRACE_CLASS_PROTOCOL",
             "TRACE_CLASS_ALGORITHM",
             "TRACE_CLASS_SESSION",
             "TRACE_CLASS_TRANSACTION",
             "TRACE_CLASS_MAPPING"},
        Values{
             "TRACE_CLASS_CALL",
             "TRACE_CLASS_INIT",
             "TRACE_CLASS_ENGINE",
             "TRACE_CLASS_PACKET",
             "TRACE_CLASS_PROTOCOL",
             "TRACE_CLASS_ALGORITHM",
             "TRACE_CLASS_SESSION",
             "TRACE_CLASS_TRANSACTION",
             "TRACE_CLASS_MAPPING"},
        ValueMap{
             "0x00000001",
             "0x00000002",
             "0x00000004",
             "0x00000008",
             "0x00000010",
             "0x00000020",
             "0x00000040",
             "0x00000080",
             "0x00000100"}
    ]
    uint32 Flags;
};
