#
# Module manifest for module 'winhttpproxy'
#
# Generated by: Microsoft Corporation
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'WinHttpProxy.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0.0'

    # ID used to uniquely identify this module
    GUID = 'c3943a61-5d72-4472-a9d8-649f13fef7bf'

    # Author of this module
    Author = 'Microsoft Corporation'

    # Company or vendor of this module
    CompanyName = 'Microsoft Corporation'

    # Copyright statement for this module
    Copyright = '(c) Microsoft Corporation. All rights reserved.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '3.0'

    # Functions to export from this module
    FunctionsToExport = @(
        'Get-WinhttpProxy',
        'Export-WinhttpProxy',
        'Reset-WinhttpProxy',
        'Import-WinhttpProxy',
        'Set-WinhttpProxy'
        )
}
