#pragma namespace("\\\\.\\root\\wmi")

#pragma deleteclass( "cdp_LibraryEventTypeClass", NOFAIL )

// {47E915BD-50E0-4dd9-ABDE-E6F98E9F015A}
// static const GUID cdp_EventClass_GUID =
// { 0x47e915bd, 0x50e0, 0x4dd9, { 0xab, 0xde, 0xe6, 0xf9, 0x8e, 0x9f, 0x1, 0x5a } };
#pragma deleteclass( "cdp_EventClass", NOFAIL )

// {09D2CF12-29BB-4fb2-B35B-AD99C670CE9A}
// static const GUID cdp_EventTraceProvider_GUID =
// { 0x9d2cf12, 0x29bb, 0x4fb2, { 0xb3, 0x5b, 0xad, 0x99, 0xc6, 0x70, 0xce, 0x9a } };
#pragma deleteclass( "cdp_EventTraceProvider", NOFAIL )


