<%
'--------------------------------------------------------------------
' Microsoft ADC
'
' Copyright (c) 1997 Microsoft Corporation. All Rights Reserved.
'
'
'
' ADO constants include file for VBScript
'
'--------------------------------------------------------------------

'---- ADCExecuteOptionEnum Values ----
Const adcExecSync=1
Const adcExecAsync=2

'---- ADCFetchOptionEnum Values ----
Const adcFetchUpFront=1
Const adcFetchBackground=2
Const adcFetchAsync=3

'---- ADCReadyStateEnum Values ----
Const adcReadyStateLoaded=2
Const adcReadyStateInteractive=3
Const adcReadyStateComplete=4
%>