#pragma namespace("\\\\.\\root\\CIMV2\\Security")

//
// Namespace \\root\CIMv2\Security\MicrosoftVolumeEncryption is created during
// BitLocker installation, and is for BitLocker only.  So, for uninstallation,
// we delete the entire namespace (and everything under it).
//
#pragma deleteinstance("__NAMESPACE.Name='MicrosoftVolumeEncryption'", nofail)
