//***************************************************************************
//
// 
//  Module: iScsi Discovery api
//
//  Purpose: 
//
//  Copyright (c) 2001 Microsoft Corporation
//
//***************************************************************************



#pragma namespace("\\\\.\\Root\\WMI")



#pragma DeleteInstance("__Win32Provider.Name=\"MSiSCSIInitiatorProvider\"", NOFAIL)
#pragma DeleteInstance("__MethodProviderRegistration.provider=\"\\\\\\\\.\\\\Root\\\\WMI:__Win32Provider.Name=\\\"MSiSCSIInitiatorProvider\\\"\"", NOFAIL)
#pragma DeleteInstance("__InstanceProviderRegistration.provider=\"\\\\\\\\.\\\\Root\\\\WMI:__Win32Provider.Name=\\\"MSiSCSIInitiatorProvider\\\"\"", NOFAIL)

#pragma DeleteClass("MSiSCSIInitiator_Portal", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_PortalGroup", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_TargetAddress", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_LUNList", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_TargetMappings", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_TargetLoginOptions", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_ConnectionInformation", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_IKEPresharedKeyAuthenticationInfo", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_TargetClass", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_PersistentLoginClass", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_iSNSServerClass", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_SendTargetPortalClass", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_InitiatorClass", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_DeviceOnSession", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_SessionClass", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_MethodClass", NOFAIL)
#pragma DeleteClass("MSiSCSIInitiator_PersistentDevices", NOFAIL)



#pragma DeleteClass("ISCSI_Path", NOFAIL)
#pragma DeleteClass("ISCSI_Supported_LB_Policies", NOFAIL)


#pragma DeleteClass("ISCSI_IP_Address", NOFAIL)
#pragma DeleteClass("ISCSI_TargetPortal", NOFAIL)
#pragma DeleteClass("ISCSI_TargetPortalGroup", NOFAIL)
#pragma DeleteClass("ISCSI_LoginOptions", NOFAIL)
#pragma DeleteClass("ISCSI_LUNList", NOFAIL)
#pragma DeleteClass("ISCSI_TargetMapping", NOFAIL)
#pragma DeleteClass("MSiSCSI_TCPIPConfig", NOFAIL)
#pragma DeleteClass("MSiSCSI_NICConfig", NOFAIL)
#pragma DeleteClass("MSiSCSI_BootConfiguration", NOFAIL)
#pragma DeleteClass("MSiSCSI_SecurityCapabilities", NOFAIL)
#pragma DeleteClass("MSiSCSI_DiscoveryConfig", NOFAIL)
#pragma DeleteClass("MSiSCSI_RADIUSConfig", NOFAIL)
#pragma DeleteClass("MSiSCSI_HBAInformation", NOFAIL)
#pragma DeleteClass("MSiSCSI_HBASessionConfig", NOFAIL)
#pragma DeleteClass("ISCSI_ConnectionStaticInfo", NOFAIL)
#pragma DeleteClass("ISCSI_SessionStaticInfo", NOFAIL)
#pragma DeleteClass("ISCSI_PortalInfo", NOFAIL)
#pragma DeleteClass("MSiSCSI_PortalInfoClass", NOFAIL)
#pragma DeleteClass("MSiSCSI_InitiatorSessionInfo", NOFAIL)
#pragma DeleteClass("MSiSCSI_InitiatorNodeFailureEvent", NOFAIL)
#pragma DeleteClass("MSiSCSI_InitiatorInstanceFailureEvent", NOFAIL)
#pragma DeleteClass("MSiSCSI_Path", NOFAIL)
#pragma DeleteClass("MSiSCSI_Suppported_LB_Policies", NOFAIL)
#pragma DeleteClass("MSiSCSI_LB_Operations", NOFAIL)
#pragma DeleteClass("MSiSCSI_QueryLBPolicy", NOFAIL)
#pragma DeleteClass("MSiSCSI_Eventlog", NOFAIL)
#pragma DeleteClass("MSiSCSI_RedirectPortalInfoClass", NOFAIL)
#pragma DeleteClass("ISCSI_RedirectSessionInfo", NOFAIL)
#pragma DeleteClass("ISCSI_RedirectPortalInfo", NOFAIL)
#pragma DeleteClass("MSiSCSI_ManagementOperations", NOFAIL)



#pragma DeleteClass("MSiSCSI_MMIPSECStats", NOFAIL)
#pragma DeleteClass("MSiSCSI_QMIPSECStats", NOFAIL)
#pragma DeleteClass("MSiSCSI_ConnectionStatistics", NOFAIL)
#pragma DeleteClass("MSiSCSI_SessionStatistics", NOFAIL)
#pragma DeleteClass("MSiSCSI_InitiatorLoginStatistics", NOFAIL)
#pragma DeleteClass("MSiSCSI_InitiatorInstanceStatistics", NOFAIL)
#pragma DeleteClass("MSiSCSI_NICPerformance", NOFAIL)
#pragma DeleteClass("MSiSCSI_RequestTimeStatistics", NOFAIL)



#pragma DeleteClass("MSiSCSI_Operations", NOFAIL)
#pragma DeleteClass("ISCSI_Persistent_Login", NOFAIL)
#pragma DeleteClass("MSiSCSI_PersistentLogins", NOFAIL)
#pragma DeleteClass("MSiSCSI_TargetMappings", NOFAIL)
#pragma DeleteClass("MSiSCSI_LUNMappingInformation", NOFAIL)
#pragma DeleteClass("MSiSCSI_SecurityConfigOperations", NOFAIL)
#pragma DeleteClass("MSiSCSI_AdapterEvent", NOFAIL)

