#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\WMI")


[Dynamic,
 Description("Windows NetworkItemFactory Trace"),
 guid("{D2A60D61-0F87-4673-A86C-9C461457FE27}"),
 locale("MS\\0x409")]
class NetworkItemFactoryTrace : EventTrace
{
    [Description ("Enable Flags"),
        ValueDescriptions{
             "tagDefault Flag",
             "tagNetworkItemFactory Flag"},
        DefineValues{
             "tagDefault",
             "tagNetworkItemFactory"},
        Values{
             "tagDefault",
             "tagNetworkItemFactory"},
        ValueMap{
             "0x00000001",
             "0x00000002"}
    ]
    uint32 Flags;
};
