#pragma namespace ( "\\\\.\\root\\cimv2\\mdm\\dmmap")

#pragma deleteclass("MDM_SurfaceHub",nofail)
#pragma deleteclass("MDM_SurfaceHub_Connect02",nofail)
#pragma deleteclass("MDM_SurfaceHub_DeviceAccount01",nofail)
#pragma deleteclass("MDM_SurfaceHub_Hours02",nofail)
#pragma deleteclass("MDM_SurfaceHub_Management01",nofail)
#pragma deleteclass("MDM_SurfaceHub_MOMAgent01",nofail)
#pragma deleteclass("MDM_SurfaceHub_Properties01",nofail)
#pragma deleteclass("MDM_SurfaceHub_SkypeForBusiness02",nofail)
#pragma deleteclass("MDM_SurfaceHub_Teams02",nofail)
#pragma deleteclass("MDM_SurfaceHub_Welcome02",nofail)
#pragma deleteclass("MDM_SurfaceHub_Whiteboard02",nofail)
#pragma deleteclass("MDM_SurfaceHub_WirelessProjection02",nofail)
#pragma deleteclass("MDM_Uefi",nofail)
#pragma deleteclass("MDM_Uefi_Identity01",nofail)
#pragma deleteclass("MDM_Uefi_Identity201",nofail)
#pragma deleteclass("MDM_Uefi_Permissions01",nofail)
#pragma deleteclass("MDM_Uefi_Permissions201",nofail)
#pragma deleteclass("MDM_Uefi_Settings01",nofail)
#pragma deleteclass("MDM_Uefi_Settings201",nofail)
#pragma deleteclass("MDM_WindowsTeam_DeviceAccount01",nofail)
#pragma deleteclass("MDM_WindowsTeam_Hours02",nofail)
#pragma deleteclass("MDM_WindowsTeam_OMSAgent01",nofail)
#pragma deleteclass("MDM_WindowsTeam_Properties01",nofail)
#pragma deleteclass("MDM_WindowsTeam_Welcome02",nofail)
#pragma deleteclass("MDM_WindowsTeam_WirelessProjection02",nofail)
#pragma deleteinstance("__MethodProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\cimv2\\\\mdm\\\\dmmap:__Win32Provider.Name=\\\"DMWmiBridgeProvSHUB\\\"\"", nofail)
#pragma deleteinstance("__InstanceProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\cimv2\\\\mdm\\\\dmmap:__Win32Provider.Name=\\\"DMWmiBridgeProvSHUB\\\"\"", nofail)
#pragma deleteinstance("__Win32Provider.Name=\"DMWmiBridgeProvSHUB\"", nofail)
