#pragma autorecover
#pragma classflags(64)
#pragma namespace("\\\\.\\root\\cimv2\\mdm")

[NamespaceSecuritySDDL("O:BAG:BAD:P(A;;0x6003F;;;BA)(A;;0x6003F;;;SY)")]
instance of __NAMESPACE
{
    Name = "dmmap";
};

#pragma autorecover
#pragma namespace("\\\\.\\root\\cimv2\\mdm\\dmmap")

Instance of __Win32Provider as $prov
{
 Name = "DMWmiBridgeProvSHUB";
 ClsId = "{9d21c8e9-da26-4d66-95e2-f2de1eb9aaab}";
 ImpersonationLevel = 1;
 HostingModel = "LocalSystemHost";
 version=0x40000001;
};

Instance of __MethodProviderRegistration
{
 Provider = $prov;
};

Instance of __InstanceProviderRegistration
{
 Provider = $prov;

 supportsGet = TRUE;
 supportsPut = TRUE;
 supportsDelete = TRUE;
 supportsEnumeration = TRUE;
 QuerySupportLevels = NULL;
};

[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_SurfaceHub
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] boolean ExchangeModernAuthEnabled;
	[read: ToSubClass, write: ToSubClass] string ProxyServers;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_SurfaceHub_Connect02
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] boolean AutoLaunch;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_SurfaceHub_DeviceAccount01
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] string DomainName;
	[read: ToSubClass, write: ToSubClass] string UserName;
	[read: ToSubClass, write: ToSubClass] string UserPrincipalName;
	[read: ToSubClass, write: ToSubClass] string Password;
	[read: ToSubClass, write: ToSubClass] string ExchangeServer;
	[read: ToSubClass, write: ToSubClass] string SipAddress;
	[read: ToSubClass, write: ToSubClass] string Email;
	[read: ToSubClass, write: ToSubClass] boolean CalendarSyncEnabled;
	[read: ToSubClass, write(FALSE): ToSubClass] sint32 ErrorContext;
	[read: ToSubClass, write: ToSubClass] sint32 PasswordRotationPeriod;
	[implemented] uint32 ValidateAndCommitMethod([In] string param);
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_SurfaceHub_Hours02
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] sint32 StartTime;
	[read: ToSubClass, write: ToSubClass] sint32 Duration;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_SurfaceHub_Management01
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] string GroupName;
	[read: ToSubClass, write: ToSubClass] string GroupSid;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_SurfaceHub_MOMAgent01
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] string WorkspaceID;
	[read: ToSubClass, write: ToSubClass] string WorkspaceKey;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_SurfaceHub_Properties01
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] string FriendlyName;
	[read: ToSubClass, write: ToSubClass] sint32 DefaultVolume;
	[read: ToSubClass, write: ToSubClass] sint32 ScreenTimeout;
	[read: ToSubClass, write: ToSubClass] sint32 SleepMode;
	[read: ToSubClass, write: ToSubClass] sint32 SessionTimeout;
	[read: ToSubClass, write: ToSubClass] sint32 SleepTimeout;
	[read: ToSubClass, write: ToSubClass] boolean AllowSessionResume;
	[read: ToSubClass, write: ToSubClass] boolean AllowAutoProxyAuth;
	[read: ToSubClass, write: ToSubClass] boolean DisableSigninSuggestions;
	[read: ToSubClass, write: ToSubClass] boolean DoNotShowMyMeetingsAndFiles;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_SurfaceHub_SkypeForBusiness02
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] string DomainName;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_SurfaceHub_Teams02
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] string Configurations;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_SurfaceHub_Welcome02
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] boolean AutoWakeScreen;
	[read: ToSubClass, write: ToSubClass] string CurrentBackgroundPath;
	[read: ToSubClass, write: ToSubClass] sint32 MeetingInfoOption;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_SurfaceHub_Whiteboard02
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] boolean SignInDisabled;
	[read: ToSubClass, write: ToSubClass] boolean TelemetryDisabled;
	[read: ToSubClass, write: ToSubClass] boolean SharingDisabled;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_SurfaceHub_WirelessProjection02
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] boolean PINRequired;
	[read: ToSubClass, write: ToSubClass] boolean Enabled;
	[read: ToSubClass, write: ToSubClass] sint32 Channel;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_Uefi
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write(FALSE): ToSubClass] string DeviceIdentifier;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_Uefi_Identity01
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write(FALSE): ToSubClass] string Current;
	[Octetstring: DisableOverride ToSubClass, read: ToSubClass, write: ToSubClass] string Apply;
	[Octetstring: DisableOverride ToSubClass, read: ToSubClass, write(FALSE): ToSubClass] string Result;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_Uefi_Identity201
{
	[key] string InstanceID;
	[key] string ParentID;
	[Octetstring: DisableOverride ToSubClass, read: ToSubClass, write: ToSubClass] string Apply;
	[Octetstring: DisableOverride ToSubClass, read: ToSubClass, write(FALSE): ToSubClass] string Result;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_Uefi_Permissions01
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write(FALSE): ToSubClass] string Current;
	[Octetstring: DisableOverride ToSubClass, read: ToSubClass, write: ToSubClass] string Apply;
	[Octetstring: DisableOverride ToSubClass, read: ToSubClass, write(FALSE): ToSubClass] string Result;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_Uefi_Permissions201
{
	[key] string InstanceID;
	[key] string ParentID;
	[Octetstring: DisableOverride ToSubClass, read: ToSubClass, write: ToSubClass] string Apply;
	[Octetstring: DisableOverride ToSubClass, read: ToSubClass, write(FALSE): ToSubClass] string Result;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_Uefi_Settings01
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write(FALSE): ToSubClass] string Current;
	[Octetstring: DisableOverride ToSubClass, read: ToSubClass, write: ToSubClass] string Apply;
	[Octetstring: DisableOverride ToSubClass, read: ToSubClass, write(FALSE): ToSubClass] string Result;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_Uefi_Settings201
{
	[key] string InstanceID;
	[key] string ParentID;
	[Octetstring: DisableOverride ToSubClass, read: ToSubClass, write: ToSubClass] string Apply;
	[Octetstring: DisableOverride ToSubClass, read: ToSubClass, write(FALSE): ToSubClass] string Result;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_WindowsTeam_DeviceAccount01
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] string DomainName;
	[read: ToSubClass, write: ToSubClass] string UserName;
	[read: ToSubClass, write: ToSubClass] string UserPrincipalName;
	[read: ToSubClass, write: ToSubClass] string Password;
	[read: ToSubClass, write: ToSubClass] sint32 PasswordRotationEnabled;
	[read: ToSubClass, write: ToSubClass] string ExchangeServer;
	[read: ToSubClass, write: ToSubClass] string SipAddress;
	[read: ToSubClass, write: ToSubClass] string Email;
	[read: ToSubClass, write: ToSubClass] boolean CalendarSyncEnabled;
	[read: ToSubClass, write(FALSE): ToSubClass] sint32 ErrorContext;
	[implemented] uint32 ValidateAndCommitMethod();
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_WindowsTeam_Hours02
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] sint32 StartTime;
	[read: ToSubClass, write: ToSubClass] sint32 Duration;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_WindowsTeam_OMSAgent01
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] string WorkspaceID;
	[read: ToSubClass, write: ToSubClass] string WorkspaceKey;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_WindowsTeam_Properties01
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] string FriendlyName;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_WindowsTeam_Welcome02
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] boolean AutoWakeScreen;
	[read: ToSubClass, write: ToSubClass] string CurrentBackgroundPath;
	[read: ToSubClass, write: ToSubClass] sint32 MeetingInfoOption;
};
[InPartition{"local-system"}: ToSubClass, dynamic: ToInstance, provider("DMWmiBridgeProvSHUB"): ToInstance]
class MDM_WindowsTeam_WirelessProjection02
{
	[key] string InstanceID;
	[key] string ParentID;
	[read: ToSubClass, write: ToSubClass] boolean PINRequired;
	[read: ToSubClass, write: ToSubClass] boolean Enabled;
	[read: ToSubClass, write: ToSubClass] sint32 Channel;
};
