#pragma autorecover

//
// This code is duplicated in the Microsoft.AppV.AppVClientWmi.mof file. If any changes are made to this file
// they must be made in the Microsoft.AppV.AppVClientWmi.mof also.
//

#pragma namespace("\\\\.\\root\\Appv")

//NOFAIL means continue if the class is not found

// Delete the classes
#pragma deleteclass("AppvClientApplication",NOFAIL) 
#pragma deleteclass("AppvClientAsset",NOFAIL) 
#pragma deleteclass("AppvClientPackage",NOFAIL) 
#pragma deleteclass("AppvClientConnectionGroup",NOFAIL) 
#pragma deleteclass("AppvPublishingServer",NOFAIL)

// Delete the provider
#pragma deleteinstance("__Win32Provider.Name='Microsoft.AppV.AppVClientWmi'",NOFAIL)

#pragma namespace("\\\\.\\root")

// Delete the Appv namespace
#pragma deleteinstance("__Namespace.Name='Appv'",NOFAIL)
