#pragma autorecover
#pragma classflags("forceupdate")

#pragma namespace("\\\\.\\root")

instance of __Namespace
{
        Name = "RSOP";
};

#pragma namespace("\\\\.\\root\\RSOP")

instance of __Namespace
{
        Name = "Computer";
};


#pragma namespace("\\\\.\\root\\RSOP\\Computer")


class RSOP_SubcategorySystemAuditSetting : RSOP_PolicySetting
{   
    [
        key,
        Description("Inherited from RSOP_PolicySetting"),
        Read,
        DisplayName("ID")
    ]
    string id;

    [
        key,
        Description("Inherited from RSOP_PolicySetting"),
        Read,
        DisplayName("Precedence")
    ]
    uint32 precedence;
    
    [Read] 
    string SubcategoryGuid;

    [Read]
    uint32 SettingValue;    

    [Read] 
    string SubcategoryName;
};

class RSOP_GlobalSaclSetting : RSOP_PolicySetting
{   
    [
        key,
        Description("Inherited from RSOP_PolicySetting"),
        Read,
        DisplayName("ID")
    ]
    string id;

    [
        key,
        Description("Inherited from RSOP_PolicySetting"),
        Read,
        DisplayName("Precedence")
    ]
    uint32 precedence;
    
    [Read] 
    string SettingType;
    
    [Read]
    string SettingValue;
};

class RSOP_CentralAccessPolicySetting : RSOP_PolicySetting
{   
    [
        key,
        Description("Inherited from RSOP_PolicySetting"),
        Read,
        DisplayName("ID")
    ]
    string id;

    [
        key,
        Description("Inherited from RSOP_PolicySetting"),
        Read,
        DisplayName("Precedence")
    ]
    uint32 precedence;


    [Read] 
    string CentralAccessPolicyName[];
};
