#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\WMI")

[Dynamic,
 Description("Microsoft-Windows-NetworkConnectivityStatus"),
 guid("{014DE49F-CE63-4779-BA2B-D616F6963A87}"),
 locale("MS\\0x409")]
class NCSICtlGuid : EventTrace
{
    [Description ("Enable Flags"),
        ValueDescriptions{
             "TM_NLAPROVIDER Flag",
             "TM_INTERFACEHOP Flag",
             "TM_MEDIA Flag",
             "TM_WEBPROBE Flag",
             "TM_SUPPORT Flag",
             "TM_LOCK Flag"},
        DefineValues{
             "TM_NLAPROVIDER",
             "TM_INTERFACEHOP",
             "TM_MEDIA",
             "TM_WEBPROBE",
             "TM_SUPPORT",
             "TM_LOCK"},
        Values{
             "TM_NLAPROVIDER",
             "TM_INTERFACEHOP",
             "TM_MEDIA",
             "TM_WEBPROBE",
             "TM_SUPPORT",
             "TM_LOCK"},
        ValueMap{
             "0x00000001",
             "0x00000002",
             "0x00000004",
             "0x00000008",
             "0x00000010",
             "0x00000020"}
    ]
    uint32 Flags;
};
