#pragma namespace ( "\\\\.\\root\\CIMV2")

#pragma deleteclass("MSFT_PlatformIdentifier",nofail)
#pragma deleteinstance("__MethodProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\CIMV2:__Win32Provider.Name=\\\"PlatIdProv\\\"\"", nofail)
#pragma deleteinstance("__Win32Provider.Name=\"PlatIdProv\"", nofail)
