#pragma autorecover
#pragma namespace("\\\\.\\root\\CIMV2")

Instance of __Win32Provider as $prov
{
  Name = "PlatIdProv";
  ClsId = "{F9E7E51B-800C-4AE5-A662-E90BB01156E7}";
  ImpersonationLevel = 1;
  HostingModel = "LocalServiceHost";
  version = 1073741825;
};

Instance of __MethodProviderRegistration
{
  Provider = $prov;
};

[ClassVersion("1.0.0"),locale(1033),provider("PlatIdProv")] 
class MSFT_PlatformIdentifier
{
  [implemented, static] uint32 GetPlatformIdentifier([In] string Name, [Out] string Identifier);
};
