#
# Module manifest for module 'HostComputeService'
#
# Generated by: Microsoft Corporation
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'Microsoft.HostCompute.PowerShell.Cmdlets.dll'

# Version number of this module.
ModuleVersion = '1.0.0.0'

# ID used to uniquely identify this module
GUID = 'D19D4F4C-6CA6-4071-ABCF-3AB62544A1A1'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) Microsoft Corporation. All rights reserved.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Cmdlets to export from this module
CmdletsToExport = @(
    'Get-ComputeProcess',
    'Stop-ComputeProcess')

# HelpInfo
HelpInfoUri="https://aka.ms/winsvr-2022-pshelp"
}