/* 
   \file WinsatUninstall.mof

   \author Yannis Minadakis (yannism)

   This file will unregister the mof classess registered by Winsat.mof.
   
   Copyright (c) 2005 Microsoft Corporation
*/

//  Place the WinSAT provider in the root\CIMV2 namespace
#pragma namespace("\\\\.\\ROOT\\CIMV2")

//  Destory the instance of WinSAT
#pragma deleteinstance ( "$Winsat", nofail )

//  Remove the winSAT class from the repository
#pragma deleteclass( "Win32_WinSAT", nofail )