#
# Module manifest for module 'ShieldedVMProvisioningFile'
#
# Generated by: Microsoft Corporation
#
# Generated on: 5/28/2015
#

@{

# Script module or binary module file associated with this manifest.
ModuleToProcess = 'ShieldedVmCmdlets.psm1'

# This GUID is used to uniquely identify this module.
GUID = '20acb5fb-7322-411f-a933-49a79b25f2c1'

# The author of this module.
Author = 'Microsoft Corporation'

# The company or vendor for this module.
CompanyName = 'Microsoft Corporation'

# The copyright statement for this module.
Copyright = '© Microsoft Corporation. All rights reserved.'

# The version of this module.
ModuleVersion = '1.0.0.0'

# The minimum version of PowerShell needed to use this module.
PowerShellVersion = '5.1'

# Modules that this module depends on
RequiredModules = @("Hyper-V")

# The CLR version required to use this module.
CLRVersion = '4.0'

# Functions to export from this module
FunctionsToExport = "New-ShieldedVMSpecializationDataFile","Test-ShieldingDataApplicability","Initialize-ShieldedVM","Get-ShieldedVMProvisioningStatus","Get-KeyProtectorFromShieldingDataFile"

# Help Info Uri
HelpInfoUri='https://aka.ms/winsvr-2022-pshelp' 

CompatiblePSEditions = @('Desktop', 'Core')
}
