// FepUnregister.mof : mof source for namespace unregisteration
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//
// This file will be processed by MOFCOMP utility to
// unregister the provider with the WMI repository
//

#pragma namespace("\\\\.\\root\\Microsoft")
#pragma deleteinstance("__Namespace.Name='SecurityClient'", nofail)
